[unix_http_server]
file=/tmp/supervisor.sock

[supervisord]
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:fastapi_app]
command=/Users/amitabhgiri/Documents/face-recognition-attendance-system/.venv/bin/python /Users/amitabhgiri/Documents/face-recognition-attendance-system/main.py --mode fastapi --port 5001
directory=/Users/amitabhgiri/Documents/face-recognition-attendance-system
autostart=true
autorestart=true
stderr_logfile=/tmp/flask_app.err.log
stdout_logfile=/tmp/flask_app.out.log

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock
